### PR TITLE
add bower support

### PR DESCRIPTION
**Pull request by bryanlarsen**
- uses webpack to create dist/fynx.js and dist/fynx.min.js
- create initial bower.json
- AXN and Immutable/contrib/cursor are included into fynx.js, Immutable is an external dependency
- fynx is not yet registered into bower
- Immutable 3.6.2 is required because of https://github.com/facebook/immutable-js/commit/66cddb20baeb6695c60b7c6d9f2d2016bd88e11e

### CODE REVIEW

**Comment by pluma** [comment]
Looks good. I'm not a fan of inlining the dependencies, but for `immutable/contrib/cursor` this seems to be the only way right now.

**Comment by pluma** [comment]
Any particular reason you defined axn as an external dependency? It should be available on axn.

**Comment by bryanlarsen** [comment]
@pluma:

- the 'main' entry in bower.json for axn points to the commonjs version of axn, so it's not usable out of the box
- it's tiny, so inlining it isn't expensive
- it's available as Fynx.createAction anyways

**Comment by pluma** [comment]
I should probably replace the AMD/globals wrapper in axn with a UMD one then, I guess?

Thanks.

**Comment by bryanlarsen** [comment]
just changing the 'main' entry in bower.json should be sufficient, I imagine.   But even with that fixed, IMO it's probably better to inline axn.   Unlike npm, with bower you're still doing a lot of manual management, and too many dependencies is a pain.

**Pull request merged**
