### PR TITLE
fix example in readme

### PR DESCRIPTION
**Pull request by bevanhunt**

### CODE REVIEW

**Comment by pluma** [comment]
Thanks for the heads up. I've rewritten the example section for 1.6. I hope it is a bit clearer now.

**Comment by bevanhunt** [comment]
Thanks for the update to the readme and for the new version - they are great! I found one small issue - I will submit a new PR. FYI - I created a demo app from your new readme here: https://github.com/bevanhunt/react-fynx-login-demo

**Comment by pluma** [comment]
Sweet. I'll add a link in the readme.

**Comment by bevanhunt** [comment]
Thanks!

**Pull request closed without merging**
